# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QWidget
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(526, 358)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.plainTextEdit.setPlainText(_translate("Form", "                                        ПРИЛОЖЕНИЕ\n"
                                                           "Текстовый редактор – Notepad+. Notepad+ - это миниверсия блокнота, с функциями унаследованными от приложения блокнот. Сутью этого проекта было создание текстового редактора с удобным и приятным интерфейсом, а также добавить функции, которых нет в стандартном приложении блокнот. Приложение записывает лог действий пользователя в базу данных. Кроме этого приложение может импортировать csv файлы и экспортировать в csv файлы текст, который ввёл пользователь.\n"
                                                           "При создании приложения был использован язык python, его библиотека Pyqt5 и база данных SQLiteStudio.\n"
                                                           "                                        ОСОБЕННОСТИ\n"
                                                           "Можно изменять цвет текста, тему приложения(тёмную на светлую и наоборот), toolbar, возможность вставлять картинки.\n"
                                                           "\n"
                                                           ""))


class About(Ui_Form, QWidget):
    def __init__(self, parent):
        super(About, self).__init__()
        self.setupUi(self)
        self.setWindowIcon(QtGui.QIcon('Images\\notepad_img.png'))
        self.setWindowTitle('О приложении')

